title: Create a bouncy material
hero_image: images/banner.png
description: Create a bouncy material in Unity
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Create a bouncy material
